## To implement various ensemble techniques like bagging and boosting,comparing their performance

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('C:\\Python_Training\\Python_Labs\\SLC\\In Class\\Day 4\\data1.csv')
df.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_279628684  190000.0       0      3       0     1       1     0    NaN   
1  ID_f29eb3ddd  135000.0       0      4       0     1       1     1    1.0   
2  ID_68de51c94       NaN       0      8       0     1       1     0    NaN   
3  ID_d671db89c  180000.0       0      5       0     1       1     1    1.0   
4  ID_d56d6f5f5  180000.0       0      5       0     1       1     1    1.0   

   r4h1  ...  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  SQBhogar_nin  \
0     0  ...          100    1849               1        100             0   
1     0  ...          144    4489               1        144             0   
2     0  ...          121    8464               1          0             0   
3     0  ...           81     289              16        121             4   
4     0  ...          121    1369              16        121             4   

   SQBovercrowding  SQBdependency  SQBmeaned  agesq  Target  
0         1.000000            0.0      100.0   1849       4  
1         1.000000           64.0      144.0   4489       4  
2         0.250000           64.0      121.0   8464       4  
3         1.777778            1.0      121.0    289       4  
4         1.777778            1.0      121.0   1369       4  

[5 rows x 143 columns]

In [6]:
df.shape

(9557, 143)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9557 entries, 0 to 9556
Columns: 143 entries, Id to Target
dtypes: float64(8), int64(130), object(5)
memory usage: 10.4+ MB


In [7]:
df.describe()

v2a1       hacdor        rooms       hacapo         v14a  \
count  2.697000e+03  9557.000000  9557.000000  9557.000000  9557.000000   
mean   1.652316e+05     0.038087     4.955530     0.023648     0.994768   
std    1.504571e+05     0.191417     1.468381     0.151957     0.072145   
min    0.000000e+00     0.000000     1.000000     0.000000     0.000000   
25%    8.000000e+04     0.000000     4.000000     0.000000     1.000000   
50%    1.300000e+05     0.000000     5.000000     0.000000     1.000000   
75%    2.000000e+05     0.000000     6.000000     0.000000     1.000000   
max    2.353477e+06     1.000000    11.000000     1.000000     1.000000   

            refrig         v18q        v18q1         r4h1         r4h2  ...  \
count  9557.000000  9557.000000  2215.000000  9557.000000  9557.000000  ...   
mean      0.957623     0.231767     1.404063     0.385895     1.559171  ...   
std       0.201459     0.421983     0.763131     0.680779     1.036574  ...   
min       0.000000     0.000000     1.000000     0.000000     0.000000  ...   
25%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
50%       1.000000     0.000000     1.000000     0.000000     1.000000  ...   
75%       1.000000     0.000000     2.000000     1.000000     2.000000  ...   
max       1.000000     1.000000     6.000000     5.000000     8.000000  ...   

       SQBescolari       SQBage  SQBhogar_total    SQBedjefe  SQBhogar_nin  \
count  9557.000000  9557.000000     9557.000000  9557.000000   9557.000000   
mean     74.222769  1643.774302       19.132887    53.500262      3.844826   
std      76.777549  1741.197050       18.751395    78.445804      6.946296   
min       0.000000     0.000000        1.000000     0.000000      0.000000   
25%      16.000000   289.000000        9.000000     0.000000      0.000000   
50%      36.000000   961.000000       16.000000    36.000000      1.000000   
75%     121.000000  2601.000000       25.000000    81.000000      4.000000   
max     441.000000  9409.000000      169.000000   441.000000     81.000000   

       SQBovercrowding  SQBdependency    SQBmeaned        agesq       Target  
count      9557.000000    9557.000000  9552.000000  9557.000000  9557.000000  
mean          3.249485       3.900409   102.588867  1643.774302     3.302292  
std           4.129547      12.511831    93.516890  1741.197050     1.009565  
min           0.040000       0.000000     0.000000     0.000000     1.000000  
25%           1.000000       0.111111    36.000000   289.000000     3.000000  
50%           2.250000       0.444444    81.000000   961.000000     4.000000  
75%           4.000000       1.777778   134.560010  2601.000000     4.000000  
max          36.000000      64.000000  1369.000000  9409.000000     4.000000  

[8 rows x 138 columns]

In [8]:
df.isna().sum()

Id                    0
v2a1               6860
hacdor                0
rooms                 0
hacapo                0
                   ... 
SQBovercrowding       0
SQBdependency         0
SQBmeaned             5
agesq                 0
Target                0
Length: 143, dtype: int64

In [9]:
df=df.fillna(df.mean())

In [10]:
df.isna().sum()

Id                 0
v2a1               0
hacdor             0
rooms              0
hacapo             0
                  ..
SQBovercrowding    0
SQBdependency      0
SQBmeaned          0
agesq              0
Target             0
Length: 143, dtype: int64

In [11]:
X=df.iloc[:,1:-1]
y=df.loc[:,'Target']

In [12]:
X.loc[:,'dependency'].replace(to_replace=dict(yes=1, no=0), inplace=True)
X.loc[:,'edjefe'].replace(to_replace=dict(yes=1, no=0), inplace=True)
X.loc[:,'edjefa'].replace(to_replace=dict(yes=1, no=0), inplace=True)

In [13]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_X = LabelEncoder()
X.loc[:,'idhogar'] = labelEncoder_X.fit_transform(X.loc[:,'idhogar'])

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=10,test_size=0.3)

## Bagging

## Bagging Classifier

In [17]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree

bagging_model=BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))

bagging_model.fit(X_train,y_train)

print('Score for bagging model',bagging_model.score(X_test,y_test))

Score for bagging model 0.9281729428172942


In [20]:
from sklearn.metrics import confusion_matrix,classification_report

y_test_pred_bagging=bagging_model.predict(X_test)

print('Confusuion matrix for bagging model:','\n',confusion_matrix(y_test,y_test_pred_bagging))

Confusuion matrix for bagging model: 
 [[ 186   18    6   30]
 [   6  401   11   34]
 [   0   25  284   41]
 [   7   17   11 1791]]


In [21]:
print('Classification report for bagging model:','\n',classification_report(y_test,y_test_pred_bagging))

Classification report for bagging model: 
               precision    recall  f1-score   support

           1       0.93      0.78      0.85       240
           2       0.87      0.89      0.88       452
           3       0.91      0.81      0.86       350
           4       0.94      0.98      0.96      1826

   micro avg       0.93      0.93      0.93      2868
   macro avg       0.91      0.86      0.89      2868
weighted avg       0.93      0.93      0.93      2868



## Random Forest

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=1)
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [24]:
y_test_pred_rf=rf.predict(X_test)

print('Score for RF model',rf.score(X_test,y_test))
print('Confusuion matrix for RF model:','\n',confusion_matrix(y_test,y_test_pred_rf))

Score for RF model 0.8863319386331938
Confusuion matrix for RF model: 
 [[ 165   27    9   39]
 [   9  354   13   76]
 [   2   27  249   72]
 [   5   30   17 1774]]


## Boosting

### AdaBoost

In [30]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(random_state=1,n_estimators=100)
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=100, random_state=1)

In [31]:
print('Score for AdaBoost model',ada.score(X_test,y_test))

Score for AdaBoost model 0.6813110181311018


## Gradient Boosting

In [36]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(random_state=1,learning_rate=0.1)
gb.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=1,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [39]:
print('Score for Gradient Boosting model',gb.score(X_test,y_test))

Score for Gradient Boosting model 0.7517433751743375


## Stacking

In [44]:
from sklearn.ensemble import VotingClassifier

bagging_model=BaggingClassifier(tree.DecisionTreeClassifier(random_state=1))
rf=RandomForestClassifier(random_state=1)
ada=AdaBoostClassifier(random_state=1,n_estimators=100)
gb=GradientBoostingClassifier(random_state=1,learning_rate=0.2)

clf=VotingClassifier(estimators=[('Bagging',bagging_model),('RF',rf),('ADA',ada),('GBC',gb)],voting='hard')

clf.fit(X_train,y_train)

VotingClassifier(estimators=[('Bagging', BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2...    subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False))],
         flatten_transform=None, n_jobs=None, voting='hard', weights=None)

In [45]:
print('Score for Voting Classifier model for hard voting',clf.score(X_test,y_test))

Score for Voting Classifier model for hard voting 0.8800557880055788


In [46]:
clf=VotingClassifier(estimators=[('Bagging',bagging_model),('RF',rf),('ADA',ada),('GBC',gb)],voting='soft',weights=[2,1,2,2])

clf.fit(X_train,y_train)

VotingClassifier(estimators=[('Bagging', BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2...    subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False))],
         flatten_transform=None, n_jobs=None, voting='soft',
         weights=[2, 1, 2, 2])

In [47]:
print('Score for Voting Classifier model for soft voting',clf.score(X_test,y_test))

Score for Voting Classifier model for soft voting 0.900976290097629
